apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmrs-tenant.backend.fullname" . }}-db-root
  labels:
    {{- include "openmrs-tenant.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "shared.db.rootPassword is required" .Values.shared.db.rootPassword | quote }}
